database:
  hostname:
  username:
  password:
  database:

report_from_days_ago: 30

email_report:
  from:
  to:
  subject:
  smtp_server:
  smtp_port: 25
  smtp_auth: false
  smtp_user:
  smtp_pass:
